# Site settings
title: "Amirhossein Najafi Resume"
description: "I’m currently pursuing my Master’s in Computer Science, with a keen interest in Artificial Intelligence, Machine Learning, and Data Science. I’ve had hands-on experience designing Neural Networks and implementing Machine Learning models in real-world scenarios. When it comes to programming languages, I’m comfortable with Python"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Amirhossein Najafi"
  resume_title: "AI Engineer and Data Scientist"


# used for the contact button in _layouts/resume.html
resume_contact_email:           "a.najafi@email.kntu.ac.ir"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
resume_contact_address:         "Tehran, Tehran"

resume_header_contact_info: "AI Lab of Dr. Ahmadi, K.N. Toosi University, Tehran, Iran • a.najafi@email.kntu.ac.ir"
display_header_contact_info:    "true"

resume_header_intro: "<p>AI Engineer. 3+ years of AI Engineering and Research experience.

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/6amir6hosein6"
#  resume_twitter_url:           "http://twitter.com/iHarnoorSingh"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/6amir6hosein6/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
